// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ9psX3PcmyJebIKAypVIvqyZCPl-PhsE',
    appId: '1:334794070298:web:bb30bb200bb33076f5f4a3',
    messagingSenderId: '334794070298',
    projectId: 'e-commerce-app-f4a86',
    authDomain: 'e-commerce-app-f4a86.firebaseapp.com',
    storageBucket: 'e-commerce-app-f4a86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO_oLpaxHOUrODr4SBBXD01aLs9Ko8pvY',
    appId: '1:334794070298:ios:2055ef6627b7beacf5f4a3',
    messagingSenderId: '334794070298',
    projectId: 'e-commerce-app-f4a86',
    storageBucket: 'e-commerce-app-f4a86.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO_oLpaxHOUrODr4SBBXD01aLs9Ko8pvY',
    appId: '1:334794070298:ios:2055ef6627b7beacf5f4a3',
    messagingSenderId: '334794070298',
    projectId: 'e-commerce-app-f4a86',
    storageBucket: 'e-commerce-app-f4a86.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ9psX3PcmyJebIKAypVIvqyZCPl-PhsE',
    appId: '1:334794070298:web:aaa9735939c5d7abf5f4a3',
    messagingSenderId: '334794070298',
    projectId: 'e-commerce-app-f4a86',
    authDomain: 'e-commerce-app-f4a86.firebaseapp.com',
    storageBucket: 'e-commerce-app-f4a86.firebasestorage.app',
  );
}
